/* GENERATED by tools/build_td_params.py from src/data/apvts.json.
 *
 * Do not hand-edit: ids, types, ranges, defaults and option lists come from
 * the plug-in source via tools/parse_td_params.py. Edit the prose table in
 * build_td_params.py and re-run it.
 *
 * Written this way because the previous hand-maintained version published 32
 * parameter ids the plug-in has never had, 18 wrong ranges or defaults, both
 * note-division lists reversed, and Diffusion as a knob when it is a switch.
 */

export const PLUGIN_VERSION = "4.0.2";

export const APVTS_PARAMETERS = [
  { id: "master_enable", name: "Power", category: "Global & Sync", type: "toggle", defaultValue: true, description: "Master DSP processing toggle with click-free crossfaded bypass.", dspDetail: "Executes realtime-safe crossfaded bypass without digital transients." },
  { id: "tempo_sync_enable", name: "Tempo Sync", category: "Global & Sync", type: "toggle", defaultValue: true, description: "Switches between millisecond delay timing and host tempo sync.", dspDetail: "Queries the DAW transport clock, or uses Manual BPM, to turn a note division into a sample interval." },
  { id: "bpm_manual", name: "Manual BPM", category: "Global & Sync", type: "knob", defaultValue: 120.0, min: 20.0, max: 300.0, step: 0.1, unit: "BPM", description: "Manual project tempo clock source when host transport sync is unlinked.", dspDetail: "Provides a deterministic master clock fallback for unlinked standalone or host sessions." },
  { id: "note_division_left", name: "Left Division", category: "L/R Timing", type: "choice", defaultValue: 8, options: ["1/1 Whole", "1/2 Half", "1/2D Dotted", "1/2T Triplet", "1/4 Quarter", "1/4D Dotted", "1/4T Triplet", "1/8 Eighth", "1/8D Dotted", "1/8T Triplet", "1/16 16th", "1/16D Dotted", "1/16T Triplet", "1/32 32nd", "1/32D Dotted", "1/32T Triplet"], description: "Rhythmic note division for the left delay channel.", dspDetail: "Selects one of sixteen grid positions, from a whole note down to a 32nd triplet." },
  { id: "note_division_right", name: "Right Division", category: "L/R Timing", type: "choice", defaultValue: 7, options: ["1/1 Whole", "1/2 Half", "1/2D Dotted", "1/2T Triplet", "1/4 Quarter", "1/4D Dotted", "1/4T Triplet", "1/8 Eighth", "1/8D Dotted", "1/8T Triplet", "1/16 16th", "1/16D Dotted", "1/16T Triplet", "1/32 32nd", "1/32D Dotted", "1/32T Triplet"], description: "Rhythmic note division for the right delay channel.", dspDetail: "Set independently of the left channel, which is what produces asymmetric stereo patterns." },
  { id: "delay_ms_left", name: "Left Time", category: "L/R Timing", type: "knob", defaultValue: 375.0, min: 1.0, max: 5000.0, step: 0.1, unit: "ms", description: "Free millisecond delay time for the left channel when Sync is off.", dspDetail: "Direct millisecond buffer offset using fractional-sample interpolation." },
  { id: "delay_ms_right", name: "Right Time", category: "L/R Timing", type: "knob", defaultValue: 250.0, min: 1.0, max: 5000.0, step: 0.1, unit: "ms", description: "Free millisecond delay time for the right channel when Sync is off.", dspDetail: "Independent right-channel offset, for slapbacks that are not a musical division." },
  { id: "feedback_left_pct", name: "Feedback Left", category: "Feedback & Routing", type: "knob", defaultValue: 40.0, min: 0.0, max: 98.0, step: 0.1, unit: "%", description: "Feedback gain for the left delay buffer.", dspDetail: "Stops short of 100% by design: the loop is bounded so it cannot run away." },
  { id: "feedback_right_pct", name: "Feedback Right", category: "Feedback & Routing", type: "knob", defaultValue: 40.0, min: 0.0, max: 98.0, step: 0.1, unit: "%", description: "Feedback gain for the right delay buffer.", dspDetail: "Stops short of 100% by design: the loop is bounded so it cannot run away." },
  { id: "ping_pong_enable", name: "Ping-Pong", category: "Feedback & Routing", type: "toggle", defaultValue: true, description: "Engages cross-channel stereo ping-pong routing.", dspDetail: "Switches the feedback matrix so repeats alternate across the stereo field." },
  { id: "hp_filter_hz", name: "High-Pass Filter", category: "Tone Shaping", type: "knob", defaultValue: 80.0, min: 20.0, max: 20000.0, unit: "Hz", description: "High-pass filter inside the feedback loop.", dspDetail: "Removes low-end build-up from decaying repeats, so the echo does not crowd the source." },
  { id: "lp_filter_hz", name: "Low-Pass Filter", category: "Tone Shaping", type: "knob", defaultValue: 8000.0, min: 20.0, max: 20000.0, unit: "Hz", description: "Low-pass filter inside the feedback loop.", dspDetail: "Darkens successive repeats, which is what makes a long tail sit behind the dry signal." },
  { id: "feedback_saturation_pct", name: "Feedback Saturation", category: "Tone Shaping", type: "knob", defaultValue: 30.0, min: 0.0, max: 100.0, step: 0.1, unit: "%", description: "Soft-clipping stage inside the feedback path.", dspDetail: "Adds progressive harmonic content to each pass, so repeats colour as they decay." },
  { id: "width_pct", name: "Stereo Width", category: "Spatial & Output", type: "knob", defaultValue: 100.0, min: 0.0, max: 200.0, step: 0.1, unit: "%", description: "Mid/side width of the wet signal, from mono to twice natural width.", dspDetail: "Scales side energy relative to mid." },
  { id: "mix_pct", name: "Mix", category: "Spatial & Output", type: "knob", defaultValue: 35.0, min: 0.0, max: 100.0, step: 0.1, unit: "%", description: "Dry/wet output blend.", dspDetail: "Crossfades the unprocessed input against the processed signal." },
  { id: "modulation_enable", name: "Modulation Enable", category: "Modulation", type: "toggle", defaultValue: false, description: "Engages LFO modulation of the delay time.", dspDetail: "A low-frequency oscillator moves the delay tap read position." },
  { id: "modulation_depth_pct", name: "Modulation Depth", category: "Modulation", type: "knob", defaultValue: 0.0, min: 0.0, max: 100.0, step: 0.1, unit: "%", description: "How far the LFO moves the delay time.", dspDetail: "Off by default, so enabling modulation alone changes nothing until depth is raised." },
  { id: "modulation_rate_hz", name: "Modulation Rate", category: "Modulation", type: "knob", defaultValue: 0.35, min: 0.05, max: 8.0, step: 0.01, unit: "Hz", description: "LFO speed when modulation is not tempo-synced.", dspDetail: "Skewed so the slow end, where chorus and tape wow live, gets most of the travel." },
  { id: "modulation_stereo_pct", name: "Modulation Stereo Spread", category: "Modulation", type: "knob", defaultValue: 50.0, min: 0.0, max: 100.0, step: 0.1, unit: "%", description: "How far apart the left and right LFOs run.", dspDetail: "A percentage, not an angle: 0% moves both channels together, 100% is the widest offset the engine applies." },
  { id: "character_mode", name: "Character Mode", category: "Character System", type: "choice", defaultValue: 0, options: ["Digital", "Tape", "Analog"], description: "Selects between three voicings for the delay path.", dspDetail: "Digital is full bandwidth; Tape and Analog each impose their own bandwidth and saturation behaviour." },
  { id: "ducking_enable", name: "Ducking Enable", category: "Ducking Engine", type: "toggle", defaultValue: false, description: "Ducks the wet signal while the input is playing.", dspDetail: "Tracks the input envelope and attenuates the wet path against it." },
  { id: "ducking_amount_pct", name: "Ducking Amount", category: "Ducking Engine", type: "knob", defaultValue: 75.0, min: 0.0, max: 100.0, step: 0.1, unit: "%", description: "How far the wet signal drops while the input is present.", dspDetail: "Sets the maximum attenuation applied to the wet path." },
  { id: "ducking_attack_ms", name: "Ducking Attack", category: "Ducking Engine", type: "knob", defaultValue: 15.0, min: 1.0, max: 100.0, step: 0.1, unit: "ms", description: "How quickly the duck engages on a transient.", dspDetail: "Skewed towards the short end, where the useful settings are." },
  { id: "ducking_release_ms", name: "Ducking Release", category: "Ducking Engine", type: "knob", defaultValue: 200.0, min: 20.0, max: 2000.0, step: 1.0, unit: "ms", description: "How quickly the wet signal returns after the input stops.", dspDetail: "Skewed towards the short end, where the useful settings are." },
  { id: "modulation_sync_enable", name: "Modulation Sync", category: "Modulation", type: "toggle", defaultValue: false, description: "Locks the LFO rate to the host tempo.", dspDetail: "Replaces the free-running rate with a note division." },
  { id: "modulation_note_division", name: "Modulation Division", category: "Modulation", type: "choice", defaultValue: 4, options: ["1/1 Whole", "1/2 Half", "1/2D Dotted", "1/2T Triplet", "1/4 Quarter", "1/4D Dotted", "1/4T Triplet", "1/8 Eighth", "1/8D Dotted", "1/8T Triplet", "1/16 16th", "1/16D Dotted", "1/16T Triplet", "1/32 32nd", "1/32D Dotted", "1/32T Triplet"], description: "Note division for the tempo-synced LFO.", dspDetail: "The same sixteen-position grid the delay times use." },
  { id: "input_trim_db", name: "Input Trim", category: "Gain Structure", type: "knob", defaultValue: 0.0, min: -24.0, max: 12.0, step: 0.1, unit: "dB", description: "Input gain before delay processing.", dspDetail: "Scales the signal entering the delay buffer." },
  { id: "wet_gain_db", name: "Wet Gain", category: "Gain Structure", type: "knob", defaultValue: 0.0, min: -24.0, max: 12.0, step: 0.1, unit: "dB", description: "Level of the wet path alone.", dspDetail: "Adjusts the processed signal before it is summed with the dry." },
  { id: "output_trim_db", name: "Output Trim", category: "Gain Structure", type: "knob", defaultValue: 0.0, min: -24.0, max: 12.0, step: 0.1, unit: "dB", description: "Master output level.", dspDetail: "Final trim after the dry/wet mix." },
  { id: "freeze_enable", name: "Freeze", category: "Advanced Processing", type: "toggle", defaultValue: false, description: "Holds the current buffer contents indefinitely.", dspDetail: "Locks buffer playback and mutes new input, so the captured phrase loops." },
  { id: "reverse_enable", name: "Reverse", category: "Advanced Processing", type: "toggle", defaultValue: false, description: "Plays the delay buffer backwards.", dspDetail: "Reads the buffer in reverse frame order." },
  { id: "diffusion_enable", name: "Diffusion", category: "Advanced Processing", type: "toggle", defaultValue: false, description: "Smears discrete repeats into a denser tail.", dspDetail: "An all-pass network on the delay taps. It is a switch, not an amount." },
] as const;

/** The filter groups the design system exposes as category chips. */
export const PARAMETER_GROUPS = [
  'Global & Sync',
  'L/R Timing',
  'Tone Shaping',
  'Character System',
  'Ducking Engine',
  'Modulation',
  'Output',
] as const;

export type ParameterGroup = (typeof PARAMETER_GROUPS)[number];

/** Folds the manifest's fine-grained categories onto the seven chips. */
export const GROUP_BY_CATEGORY: Record<string, ParameterGroup> = {
  'Global & Sync': 'Global & Sync',
  'L/R Timing': 'L/R Timing',
  'Feedback & Routing': 'L/R Timing',
  'Tone Shaping': 'Tone Shaping',
  'Character System': 'Character System',
  'Advanced Processing': 'Character System',
  'Ducking Engine': 'Ducking Engine',
  Modulation: 'Modulation',
  'Spatial & Output': 'Output',
  'Gain Structure': 'Output',
};
